### ISSUE TITLE
no icon for extension

### ISSUE THREAD

**Issue by ghost** [nagyv/gmail-emoji#1]
I just installed the old-gmail-emoji from the Chrome webstore.
I saw the installation confirmation by the screen's  icon area upper right corner.--
   but  NO  ICON -- therefore cannot access.  Please fix

**Comment by nagyv** [comment]
Hi,

The icon for the drop-down is present only on mail.google.com. Have you checked it there or on some other site?

**Comment by ghost** [comment]
Oh  ok, I had the gmail shortcut in the bookmarks bar but I got the
shortcut from that address given, and now I see it.. That's weird.  Thank
you for your quick response.
