### ISSUE TITLE
Grey Background

### ISSUE THREAD

**Issue by dev-mcm** [nagyv/gmail-emoji#2]
I noticed when using this extension there's a grey background behind the animated emojis, is that a problem unique to my browser?

See screenshot below

![image](https://cloud.githubusercontent.com/assets/6991397/10021703/41372e4a-6117-11e5-9352-284a380186d4.png)

**Comment by peterclark13** [comment]
Even many of the non-animated emoji have the grey background:
![12-17-2015 12-58-03 pm](https://cloud.githubusercontent.com/assets/16340283/11877627/7f93d0ea-a4be-11e5-9aff-e467dab6e2dc.png)

thanks for your work!

**Comment by peterclark13** [comment]
thanks Viktor - looks great now.

Great add on extension!
Peter

On Fri, Dec 25, 2015 at 4:49 AM, Viktor Nagy notifications@github.com
wrote:

> Closed #2 https://github.com/nagyv/gmail-emoji/issues/2 via feb68f9
> https://github.com/nagyv/gmail-emoji/commit/feb68f96ecb897c33ce6c85c114bb38913f7d82c
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nagyv/gmail-emoji/issues/2#event-500478035.

## 

www.shamansflame.com
www.allthingshealing.com/shamanism-healing.php
