### ISSUE TITLE
Extention icon isn't showing

### ISSUE THREAD

**Issue by LindyGal** [nagyv/gmail-emoji#3]
Added the extention to Chrome, and no icon is displaying.

**Comment by nagyv** [comment]
This is weird. Do you have gmail open? The icon in the location bar shows only on the mail.google.com domain?

**Comment by LindyGal** [comment]
Yes, gmail is open.

Yvonne Conybeare
Executive Director
_Harlem Swings!_
_www.harlemswings.com http://www.harlemswings.com_
